version: "3"
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.6.6-32.0
    ports:
      - "389:389"
      - "636:636"
    environment:
      ARCHIVE_HOST: gunter-nb
      STORAGE_DIR: /storage/fs1
    volumes:
      - /var/local/dcm4chee-arc/ldap:/var/lib/openldap/openldap-data
      - /var/local/dcm4chee-arc/slapd.d:/etc/openldap/slapd.d
  db:
    image: dcm4che/postgres-dcm4chee:16.2-32
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pacsdb
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: pacs
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/db:/var/lib/postgresql/data
  arc:
    image: dcm4che/dcm4chee-arc-psql:azul-zing-5.32.1
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
      - "8787:8787"
      - "11112:11112"
      - "2762:2762"
      - "2575:2575"
      - "12575:12575"
    environment:
      WILDFLY_ADMIN_USER: admin
      WILDFLY_ADMIN_PASSWORD: admin
      WILDFLY_DEPLOY_UI: "false"
      WILDFLY_PACSDS_USE_CCM: "false"
      POSTGRES_DB: pacsdb
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: pacs
      WILDFLY_CHOWN: /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
      JAVA_OPTS: -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -agentlib:jdwp=transport=dt_socket,address=*:8787,server=y,suspend=n
    depends_on:
      - ldap
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/wildfly:/opt/wildfly/standalone
      - /var/local/dcm4chee-arc/storage:/storage
  ui:
    image: dcm4che/dcm4chee-arc-psql:azul-zing-5.32.1
    ports:
      - "18080:18080"
      - "18443:18443"
      - "19990:19990"
      - "19993:19993"
      - "8888:8888"
    environment:
      WILDFLY_ADMIN_USER: admin
      WILDFLY_ADMIN_PASSWORD: admin
      WILDFLY_DEPLOY_UI: only
      WILDFLY_PACSDS_USE_CCM: "false"
      DCM4CHEE_ARC_URLS: http://gunter-nb:8080/dcm4chee-arc
      HTTP_PORT: 18080
      HTTPS_PORT: 18443
      MANAGEMENT_HTTP_PORT: 19990
      MANAGEMENT_HTTPS_PORT: 19993
      WILDFLY_WAIT_FOR: arc:8080
      JAVA_OPTS: -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -agentlib:jdwp=transport=dt_socket,address=*:8888,server=y,suspend=n
    depends_on:
      - arc
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/ui:/opt/wildfly/standalone
